"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

import os
from pathlib import Path

# 1. إعدادات المسارات الأساسية للمشروع
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-av=1l$m2=bk^2s3nmm+)h7hks0z5e4ejs^4o3q29gbs4sy2kxt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# السماح بالوصول للموقع محلياً ومن أي مكان أثناء التطوير
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']


# 2. التطبيقات المثبتة في المشروع
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'inventory',  # تطبيق السيارات الخاص بك
]

# 3. البرمجيات الوسيطة (Middleware) مرتبة بشكل صحيح
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# 4. إعدادات القوالب (نسخة واحدة نظيفة تشمل مجلد templates الرئيسي)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # التعديل هنا: إضافة مسار المجلد الرئيسي للقوالب
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# 5. إعدادات الاتصال بقاعدة بيانات PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'car_db',         # اسم قاعدة البيانات الخاصة بك
        'USER': 'postgres',       # المستخدم الافتراضي
        'PASSWORD': '123456',     # كلمة مرور PostgreSQL الخاصة بك
        'HOST': '127.0.0.1',
        'PORT': '5432',           # المنفذ الافتراضي لـ Postgres
    }
}


# 6. شروط التحقق من قوة كلمة المرور لمسؤولي النظام
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 7. إعدادات اللغة والوقت والتاريخ للمشروع
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# 8. إعدادات الملفات الثابتة (CSS, JS) وملفات الميديا (صور السيارات المرفوعة)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# 9. إعدادات نظام طبقات القنوات (تصحيح الاسم الإملائي للـ Channels)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# 10. إعدادات الـ CORS لمشاركة الموارد بأمان
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# 11. إعدادات الجلسات لحفظ بيانات السيارة والعميل أثناء عملية الدفع الإلكتروني
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = False  # القيمة False لتناسب بيئة التطوير المحلية عبر HTTP العادي


# 12. إعدادات توجيه نظام الحماية وتجربة تسجيل الدخول والخروج (الحل النهائي للـ 404)
LOGIN_URL = 'login'              # توجيه المستخدم غير المسجل لصفحة الدخول عند محاولة التعليق أو الحجز
LOGIN_REDIRECT_URL = 'index'     # أين يذهب المستخدم مباشرة بعد نجاح تسجيل الدخول
LOGOUT_REDIRECT_URL = 'index'    # أين يتم توجيهه بعد تسجيل الخروج

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'