# Generated by Django 6.0.4 on 2026-05-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='الماركة')),
                ('model_name', models.CharField(max_length=100, verbose_name='طراز السيارة')),
                ('year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('condition', models.CharField(choices=[('New', 'جديد'), ('Used', 'مستعمل')], max_length=20, verbose_name='حالة السيارة')),
                ('engine_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المحرك')),
                ('engine_capacity', models.CharField(blank=True, max_length=20, null=True, verbose_name='سعة المحرك')),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True, verbose_name='القوة الحصانية')),
                ('transmission', models.CharField(blank=True, choices=[('Auto', 'أوتوماتيك'), ('Manual', 'يدوي')], max_length=50, null=True, verbose_name='ناقل الحركة')),
                ('drive_train', models.CharField(blank=True, max_length=50, null=True, verbose_name='نظام الدفع')),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الوقود')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='الممشى (كيلومتر)')),
                ('exterior_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون الخارجي')),
                ('body_style', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الهيكل')),
                ('rims_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='مقاس الجنوط')),
                ('sunroof', models.CharField(blank=True, choices=[('None', 'بدون'), ('Standard', 'فتحة سقف'), ('Panoramic', 'بانوراما')], max_length=50, null=True, verbose_name='فتحة السقف')),
                ('lighting', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الإضاءة')),
                ('sensors', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحساسات الخارجية')),
                ('trunk_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='نظام الشنطة')),
                ('interior_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون الداخلي')),
                ('seat_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المقاعد')),
                ('seat_features', models.CharField(blank=True, max_length=100, null=True, verbose_name='ميزات المقاعد')),
                ('screen_size', models.FloatField(blank=True, null=True, verbose_name='حجم الشاشة')),
                ('sound_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='النظام الصوتي')),
                ('airbags_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الوسائد الهوائية')),
                ('cruise_control', models.CharField(blank=True, max_length=50, null=True, verbose_name='مثبت السرعة')),
                ('cameras', models.CharField(blank=True, max_length=100, null=True, verbose_name='نظام الكاميرات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف إضافي')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='صورة السيارة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاحة للعرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'سيارة',
                'verbose_name_plural': 'السيارات',
                'db_table': 'cars_car',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوكيل')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع / العنوان')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/', verbose_name='صورة الوكالة')),
            ],
            options={
                'verbose_name': 'وكيل / مخزن',
                'verbose_name_plural': 'الوكلاء والمخازن',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('status', models.CharField(choices=[('pending', 'انتظار دفع العربون'), ('paid', 'تم دفع العربون'), ('fully_paid', 'تم دفع كامل المبلغ'), ('expired', 'منتهي الصلاحية'), ('canceled', 'ملغي')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='رقم العملية')),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ دفع العربون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='inventory.car', verbose_name='السيارة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inventory.inventory', verbose_name='الوكيل')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_cars', to='inventory.inventory', verbose_name='الوكيل المسؤول'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='الوكيل المفضّل')),
            ],
            options={
                'verbose_name': 'مفضلة',
                'verbose_name_plural': 'المفضلات',
                'unique_together': {('user', 'inventory')},
            },
        ),
    ]
