# Generated by Django 6.0.4 on 2026-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'متاحة للبيع'), ('reserved', 'محجوزة مؤقتاً'), ('sold', 'مباعة بالكامل')], default='available', max_length=20, verbose_name='حالة العرض والبيع'),
        ),
    ]
