# Generated by Django 6.0.4 on 2026-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='رد الإدارة'),
        ),
        migrations.AddField(
            model_name='message',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='رد الإدارة'),
        ),
    ]
