# Generated by Django 6.0.4 on 2026-04-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='الماركة')),
                ('model_name', models.CharField(max_length=100, verbose_name='طراز السيارة')),
                ('year', models.PositiveIntegerField(verbose_name='سنة الصنع')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('condition', models.CharField(choices=[('New', 'جديد'), ('Used', 'مستعمل')], max_length=20, verbose_name='حالة السيارة')),
                ('engine_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المحرك')),
                ('engine_capacity', models.CharField(blank=True, max_length=20, null=True, verbose_name='سعة المحرك')),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True, verbose_name='القوة الحصانية')),
                ('transmission', models.CharField(blank=True, choices=[('Auto', 'أوتوماتيك'), ('Manual', 'يدوي')], max_length=50, null=True, verbose_name='ناقل الحركة')),
                ('drive_train', models.CharField(blank=True, max_length=50, null=True, verbose_name='نظام الدفع')),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الوقود')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='الممشى (كيلومتر)')),
                ('exterior_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون الخارجي')),
                ('body_style', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الهيكل')),
                ('rims_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='مقاس الجنوط')),
                ('sunroof', models.CharField(blank=True, choices=[('None', 'بدون'), ('Standard', 'فتحة سقف'), ('Panoramic', 'بانوراما')], max_length=50, null=True, verbose_name='فتحة السقف')),
                ('lighting', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الإضاءة')),
                ('sensors', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحساسات الخارجية')),
                ('trunk_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='نظام الشنطة')),
                ('interior_color', models.CharField(blank=True, max_length=50, null=True, verbose_name='اللون الداخلي')),
                ('seat_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المقاعد')),
                ('seat_features', models.CharField(blank=True, max_length=100, null=True, verbose_name='ميزات المقاعد')),
                ('screen_size', models.FloatField(blank=True, null=True, verbose_name='حجم الشاشة')),
                ('sound_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='النظام الصوتي')),
                ('airbags_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الوسائد الهوائية')),
                ('cruise_control', models.CharField(blank=True, max_length=50, null=True, verbose_name='مثبت السرعة')),
                ('cameras', models.CharField(blank=True, max_length=100, null=True, verbose_name='نظام الكاميرات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف إضافي')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='صورة السيارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='inventory.inventory', verbose_name='الوكيل المسؤول')),
            ],
            options={
                'verbose_name': 'سيارة',
                'verbose_name_plural': 'السيارات',
            },
        ),
    ]
